from enum import IntEnum


class ASTRO_SPIKE_RECEIVER_PROBE(IntEnum):
    COMPARTMENT_CURRENT = 1
    COMPARTMENT_VOLTAGE = 2
    SPIKE = 3


class ASTRO_IP3_INTEGRATOR_PROBE(IntEnum):
    COMPARTMENT_CURRENT = 4
    COMPARTMENT_VOLTAGE = 5
    SPIKE = 6


class ASTRO_SIC_GENERATOR_PROBE(IntEnum):
    COMPARTMENT_CURRENT = 7
    COMPARTMENT_VOLTAGE = 8


class ASTRO_SPIKE_GENERATOR_PROBE(IntEnum):
    COMPARTMENT_CURRENT = 9
    COMPARTMENT_VOLTAGE = 10
    SPIKE = 11
